name: build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          cd python_codon_tables
          python -m pytest
